services:
  php:
    build: ./provision/php
    image: php:5.6-apache
    volumes:
      - ./provision/php/php.ini:/etc/php5/fpm/php.ini
      - ./provision/apache/apache2.conf:/etc/apache2/apache2.conf
      - ./provision/apache/webhooks.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./provision/apache/fcgid.conf:/etc/apache2/mods-available/fcgid.conf
      - ./provision/fpm/webhooks.conf:/etc/php5/fpm/pool.d/webhooks.conf
      - ./provision/fpm/curl.ini:/etc/php5/fpm/conf.d/curl.ini
      - .:/srv/webhooks
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.190
    ports:
      - 80:80
      - 443:443
      - 9000:9000
version: "2"
