services:
  php:
    image: 213535807263.dkr.ecr.us-east-1.amazonaws.com/btp-webhooks:latest
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.190
    ports:
      - 80:80
      - 443:443
      - 9000:9000
version: "2"
